name: LeasingNinja in PHP – CI

on: [ push,  pull_request ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-interaction --no-ansi --no-progress

    - name: Run static analysis
      run: ./vendor/bin/phpstan analyze --no-interaction --no-ansi --no-progress

    - name: Test
      run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
